RULES: dict[str, dict[str, object]] = {
    "RULE_001": {
        "description": "Informed consent must be obtained before any study procedures begin.",
        "violation_trigger": "baseline assessments were completed prior to obtaining written informed consent",
        "fix_keywords": ["written informed consent", "before any procedure", "prior to enrollment"],
        "severity": "critical",
        "phase_restriction": None,
    },
    "RULE_002": {
        "description": "The protocol must specify the primary endpoint with a measurable definition.",
        "violation_trigger": "the primary outcome will be assessed at investigator discretion",
        "fix_keywords": ["primary endpoint", "defined as", "measured by", "RECIST criteria"],
        "severity": "major",
        "phase_restriction": None,
    },
    "RULE_003": {
        "description": "Sample size must be justified with a power calculation.",
        "violation_trigger": "the sample size of 40 subjects was chosen based on feasibility considerations alone",
        "fix_keywords": ["power calculation", "80% power", "statistical justification", "alpha 0.05"],
        "severity": "major",
        "phase_restriction": None,
    },
    "RULE_004": {
        "description": "Inclusion and exclusion criteria must be clearly listed.",
        "violation_trigger": "eligible participants will be determined by the treating physician on a case-by-case basis",
        "fix_keywords": ["inclusion criteria", "exclusion criteria", "age 18", "written criteria"],
        "severity": "major",
        "phase_restriction": None,
    },
    "RULE_005": {
        "description": "The investigator must have documented qualifications.",
        "violation_trigger": "investigator qualifications will be submitted following site initiation",
        "fix_keywords": ["investigator CV", "qualified investigator", "training certificate", "documented"],
        "severity": "critical",
        "phase_restriction": None,
    },
    "RULE_006": {
        "description": "Adverse event reporting procedures must be defined.",
        "violation_trigger": "adverse events will be handled at the clinical team's discretion without a formal reporting timeline",
        "fix_keywords": ["adverse event", "24-hour reporting", "SAE", "safety monitoring", "reporting timeline"],
        "severity": "critical",
        "phase_restriction": None,
    },
    "RULE_007": {
        "description": "Phase III protocols must specify a Data Monitoring Committee.",
        "violation_trigger": "no independent data monitoring committee has been appointed for this trial",
        "fix_keywords": ["data monitoring committee", "DMC", "DSMB", "independent review board"],
        "severity": "major",
        "phase_restriction": "Phase III",
    },
    "RULE_008": {
        "description": "Protocol must define stopping rules for early termination.",
        "violation_trigger": "the trial will continue until the planned sample size is reached regardless of interim findings",
        "fix_keywords": ["stopping rules", "futility analysis", "early termination criteria", "O'Brien-Fleming"],
        "severity": "major",
        "phase_restriction": None,
    },
    "RULE_009": {
        "description": "Randomization procedures must be described for comparative studies.",
        "violation_trigger": "subjects will be assigned to treatment groups by the site coordinator based on availability",
        "fix_keywords": ["randomization", "allocation concealment", "random sequence generation", "IWRS"],
        "severity": "major",
        "phase_restriction": None,
    },
    "RULE_010": {
        "description": "Statistical analysis plan must be pre-specified.",
        "violation_trigger": "the statistical approach will be finalized after data collection is complete",
        "fix_keywords": ["statistical analysis plan", "SAP", "pre-specified", "intent-to-treat"],
        "severity": "major",
        "phase_restriction": None,
    },
    "RULE_011": {
        "description": "Blinding procedures must be described if study is blinded.",
        "violation_trigger": "blinding will be maintained informally and unblinding procedures are not formally described",
        "fix_keywords": ["double-blind", "blinding procedure", "emergency unblinding", "blind maintenance"],
        "severity": "major",
        "phase_restriction": None,
    },
    "RULE_012": {
        "description": "Protocol version and date must be clearly stated.",
        "violation_trigger": "this document does not carry a formal version number or approval date",
        "fix_keywords": ["protocol version", "version 1.0", "effective date", "approval date"],
        "severity": "minor",
        "phase_restriction": None,
    },
}
